version: '3.8'

services:
  db:
    container_name: djangoChallange_db
    image: postgres:latest
    environment:
      - POSTGRES_DB=dev_db
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=dev_password
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  
  backend:
    container_name: djangoChallange_backend
    build:
      context: ./app
      dockerfile: Dockerfile
    command: python klarianTest/manage.py runserver 0.0.0.0:8000
    
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

volumes:
  postgres_data: